### ISSUE TITLE
Android Pie has been Released

### ISSUE THREAD

**Issue by sstruct** [dvoiss/android-versions#13]
Pie | 9.0 | 4.4.107, 4.9.84, and 4.14.42 | August 6, 2018 | 28

Time to update.

https://en.wikipedia.org/wiki/Android_version_history#Android_9.0_Pie_(API_28)

**Comment by L3au** [comment]
+1

**Comment by dvoiss** [comment]
Thanks for the issue. Merged: https://github.com/dvoiss/android-versions/pull/14.

btw @sstruct / @L3au what are either of you using this module for? 

I created it a couple years ago but didn't end up using it for the project I was working on and now I just update it when someone creates an issue, so I'm just curious 😄

**Comment by L3au** [comment]
@dvoiss Thanks for your great work. We are using this module to show readable Android versions in a monitor system according to API level which collected by App crash SDK.
